# ignore_for_file: secure_pubspec_urls
name: stagexl
version: 2.1.2
description: A fast and universal 2D rendering engine for HTML5 and Dart.
homepage: http://www.stagexl.org
repository: https://github.com/bp74/StageXL
publish_to: none

environment:
  sdk: '>=3.4.0'

documentation: http://www.stagexl.org/docs/api/index.html

dependencies:
  byte_array: ^1.0.0-nullsafety.0
  xml: '>=5.0.0 <7.0.0'
  web: ^1.0.0
  http: ^1.2.0
  meta: ^1.16.0

dev_dependencies:
  build_runner: any
  build_test: any
  build_web_compilers: any
  lints: any
  test: any
